nginx:
    build: ./nginx
    hostname: api
    ports:
      - "8080:80"
    links:
      - "php"   
    volumes:
      - ~/code/www/:/usr/share/nginx/html/

php:
    build: ./php
    links:  
      - "redis-server"
      - "mysql-server"
    volumes:
      - ~/code/www/:/usr/share/nginx/html/ 

redis-server:
    build: ./redis

mysql-server:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql-server
    environment:
      PMA_HOST: mysql-server
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
